version: "3"
services:
    node:
        build: .
        container_name: node      
        volumes:
            - ./:/home/node/app       
        networks:
            - node_address
        ports:
            - "3000:3000"
        depends_on:
            - mysqlDb
    mysqlDb:
        image: mysql:8
        container_name: mysqlDb
        restart: always
        command: --default-authentication-plugin=mysql_native_password   
        ports: 
            - "3307:3306"
        networks:
            - node_address           
        volumes:
            - mysqlDb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: Luat1134!
            MYSQL_DATABASE: blog
volumes:
    mysqlDb: 
networks:
    node_address:
        driver: bridge